/**
 * Quickstart — run with real Claude + OpenAI keys:
 *
 *   export ANTHROPIC_API_KEY=sk-ant-...
 *   export OPENAI_API_KEY=sk-...
 *   npm run example
 *
 * Uses an in-memory graph so it leaves nothing behind.
 */
import "dotenv/config";
import { ContextGraphEngine } from "../src/index.js";

const DOCS = `
# Payments Platform

The Billing Service charges customers monthly. It calls the Payments Gateway,
which integrates with Stripe. Failed charges are retried by the Dunning Worker
up to three times before the subscription is marked past_due.

Invoices are generated by the Invoicing Service and stored in Postgres. The
Billing Service reads customer plans from the Catalog Service.
`;

async function main() {
  const engine = new ContextGraphEngine({ dbPath: ":memory:" });

  console.log("Ingesting docs…");
  const ing = await engine.ingest(DOCS, { title: "Payments Platform" });
  console.log(
    `  ${ing.chunks} chunks -> +${ing.nodesCreated} entities, +${ing.edgesCreated} relationships\n`,
  );

  console.log("Reading context for an agent task:");
  const bundle = await engine.read("what happens when a charge fails?");
  console.log(bundle.prompt);

  console.log("\nAn agent contributes a learning back:");
  const c = await engine.contribute(
    "The Dunning Worker sends a Slack alert to #billing after the final failed retry.",
    { agentId: "oncall-agent" },
  );
  console.log(`  +${c.nodesCreated} entities, ${c.nodesUpdated} reinforced\n`);

  console.log("Reading again — the new learning is now part of the graph:");
  const after = await engine.read("how is the team notified about failed charges?");
  console.log(after.prompt);

  console.log("\nFinal graph:", engine.stats());
  engine.close();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
